---
jekyll: staging
settings:
  name: Cloud Manager 3.6
  nss_product: OnCommand Cloud Manager
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation sur Cloud Manager 3.6
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Le gestionnaire Cloud
      entries:
      - title: Quoi de neuf
        url: "/reference_new_occm.html"
      - title: Problèmes connus
        url: "/reference_issues.html"
      - title: Limites connues
        url: "/reference_limitations.html"
    - title: Cloud Volumes ONTAP
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap/
  - title: Concepts
    entries:
    - title: Présentation du produit
      url: "/concept_overview.html"
    - title: NetApp Cloud Central
      url: "/concept_cloud_central.html"
    - title: Comptes et autorisations
      url: "/concept_accounts_and_permissions.html"
    - title: Stockage
      entries:
      - title: Présentation
        url: "/concept_storage.html"
      - title: Tiering des données
        url: "/concept_data_tiering.html"
      - title: Gestion du stockage
        url: "/concept_storage_management.html"
      - title: Stockage WORM
        url: "/concept_worm.html"
    - title: Paires haute disponibilité
      entries:
      - title: Paires HA dans AWS
        url: "/concept_ha.html"
      - title: Paires HA dans Azure
        url: "/concept_ha_azure.html"
    - title: L'évaluation
      url: "/concept_evaluating.html"
    - title: Licences
      url: "/concept_licensing.html"
    - title: Sécurité
      url: "/concept_security.html"
    - title: Performance
      url: "/concept_performance.html"
  - title: Pour commencer
    entries:
    - title: Présentation du déploiement
      url: "/reference_deployment_overview.html"
    - title: Mise en route dans AWS
      url: "/task_getting_started_aws.html"
    - title: Mise en route dans Azure
      url: "/task_getting_started_azure.html"
    - title: Configuration de Cloud Manager
      entries:
      - title: Ajout de comptes de fournisseur cloud
        url: "/task_adding_cloud_accounts.html"
      - title: Ajout de comptes sur le site de support NetApp
        url: "/task_adding_nss_accounts.html"
      - title: Installation d'un certificat HTTPS
        url: "/task_installing_https_cert.html"
      - title: Configuration des utilisateurs et des locataires
        url: "/task_setting_up_users_tenants.html"
      - title: Configuration du système AWS KMS
        url: "/task_setting_up_kms.html"
    - title: Configuration réseau requise
      entries:
      - title: Le gestionnaire Cloud
        url: "/reference_networking_cloud_manager.html"
      - title: Cloud Volumes ONTAP pour AWS
        url: "/reference_networking_aws.html"
      - title: Configuration d'une passerelle de transit AWS
        url: "/task_setting_up_transit_gateway.html"
      - title: Cloud Volumes ONTAP pour Azure
        url: "/reference_networking_azure.html"
    - title: D'autres options de déploiement
      entries:
      - title: Conditions de l'hôte Cloud Manager
        url: "/reference_cloud_mgr_reqs.html"
      - title: Installation de Cloud Manager sur un hôte Linux
        url: "/task_installing_linux.html"
      - title: Déploiement de Cloud Manager à partir d'AWS Marketplace
        url: "/task_launching_aws_mktp.html"
      - title: Déploiement de Cloud Manager à partir d'Azure Marketplace
        url: "/task_launching_azure_mktp.html"
      - title: Déploiement de Cloud Manager dans une région Azure Government
        url: "/task_installing_azure_gov.html"
      - title: Déploiement de Cloud Manager dans la région Azure Allemagne
        url: "/task_installing_azure_germany.html"
      - title: Mise en route dans l'environnement AWS C2S
        url: "/media/c2s.pdf"
  - title: Le déploiement de Cloud Volumes ONTAP
    entries:
    - title: Avant de commencer
      url: "/reference_before.html"
    - title: Connectez-vous à Cloud Manager
      url: "/task_logging_in.html"
    - title: Planification de votre configuration
      url: "/task_planning_your_config.html"
    - title: Activation de Flash cache sur Cloud Volumes ONTAP dans AWS
      url: "/task_enabling_flash_cache.html"
    - title: Lancement d'Cloud Volumes ONTAP dans AWS
      url: "/task_deploying_otc_aws.html"
    - title: Lancement d'Cloud Volumes ONTAP dans Azure
      url: "/task_deploying_otc_azure.html"
    - title: Enregistrement des systèmes de paiement à l'utilisation
      url: "/task_registering.html"
    - title: Configuration de Cloud Volumes ONTAP
      url: "/task_setting_up_ontap_cloud.html"
  - title: Provisionnement du stockage
    entries:
    - title: Création de volumes, d'agrégats et de LUN
      url: "/task_provisioning_storage.html"
    - title: Tiering des données inactives vers le stockage objet
      url: "/task_tiering.html"
    - title: Utilisation de Cloud Volumes ONTAP comme stockage persistant
      url: "/task_connecting_kubernetes.html"
    - title: Chiffrement de volumes avec NetApp Volume Encryption
      url: "/task_encrypting_volumes.html"
    - title: Gestion du stockage existant
      url: "/task_managing_storage.html"
    - title: Provisionnement des volumes NFS depuis la vue du volume
      entries:
      - title: Passage à la vue de volume
        url: "/task_changing_volume_view.html"
      - title: Création et montage de volumes NFS
        url: "/task_provisioning_volume_view.html"
      - title: Gestion des volumes NFS
        url: "/task_managing_volume_view.html"
  - title: Gestion des données dans le cloud hybride
    entries:
    - title: Détection et gestion des clusters ONTAP
      url: "/task_discovering_ontap.html"
    - title: Réplication des données depuis et vers le cloud
      url: "/task_replicating_data.html"
    - title: Synchronisation des données vers AWS S3
      url: "/task_syncing_s3.html"
  - title: Administration d'Cloud Volumes ONTAP
    entries:
    - title: Connexion à Cloud Volumes ONTAP
      url: "/task_connecting_to_otc.html"
    - title: Mise à jour du logiciel
      url: "/task_updating_ontap_cloud.html"
    - title: Modification des configurations système
      url: "/task_modifying_ontap_cloud.html"
    - title: Arrêt et démarrage des systèmes
      url: "/task_managing_state.html"
    - title: Contrôle des coûts AWS
      url: "/task_monitoring_costs.html"
    - title: Amélioration de la protection par ransomware
      url: "/task_protecting_ransomware.html"
    - title: Ajout de systèmes existants
      url: "/task_adding_ontap_cloud.html"
    - title: Suppression de systèmes
      url: "/task_deleting_working_env.html"
  - title: Administration de Cloud Manager
    entries:
    - title: Mise à jour de Cloud Manager
      url: "/task_updating_cloud_manager.html"
    - title: Sauvegarde et restauration
      url: "/task_backing_up_restoring.html"
    - title: Suppression des environnements de travail
      url: "/task_removing.html"
    - title: Modification des comptes utilisateur
      url: "/task_editing_users.html"
    - title: Configuration des paramètres proxy
      url: "/task_configuring_proxy.html"
    - title: Renouvellement du certificat HTTPS
      url: "/task_renewing_cert.html"
    - title: Désinstallation de Cloud Manager
      url: "/task_uninstalling.html"
  - title: API et automatisation
    entries:
    - title: Guide du développeur API
      url: https://docs.netapp.com/us-en/occm/api.html
    - title: Échantillons d'automatisation
      url: "/reference_infrastructure_as_code.html"
  - title: Référence
    entries:
    - title: Forum aux questions sur l'intégration de Cloud Central
      url: "/reference_integration_faq.html"
    - title: Configurations prises en charge pour Cloud Volumes ONTAP
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_supported_configs_95.html
    - title: Régions prises en charge
      url: https://cloud.netapp.com/cloud-volumes-global-regions
    - title: Règles de groupe de sécurité pour AWS
      url: "/reference_security_groups.html"
    - title: Règles de groupe de sécurité pour Azure
      url: "/reference_security_groups_azure.html"
    - title: Autorisations
      url: "/reference_permissions.html"
    - title: Configurations par défaut
      url: "/reference_default_configs.html"
    - title: Rôles utilisateur
      url: "/reference_user_roles.html"
    - title: Liens connexes
      url: "/reference_additional_info.html"
  - title: Mentions légales
    url: "/reference_legal_notices.html"
