---
sidebar: sidebar 
permalink: reference_infrastructure_as_code.html 
keywords: ansible, playbook, automation 
summary: 'Les équipes DevOps utilisent plusieurs outils pour automatiser la configuration de nouveaux environnements et traiter l"infrastructure comme du code. Deux outils de ce type sont Ansible et Terraform. Nous avons développé des exemples Ansible et Terraform que l"équipe DevOps peut utiliser avec Cloud Manager pour automatiser et intégrer Cloud Volumes ONTAP avec l"infrastructure-as-code.' 
---
= Exemples d'automatisation pour l'infrastructure-as-code
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez les ressources disponibles sur cette page pour obtenir de l'aide sur l'intégration de Cloud Manager et de Cloud Volumes ONTAP avec votre https://["infrastructure-as-code"^].

Les équipes DevOps utilisent plusieurs outils pour automatiser la configuration de nouveaux environnements et traiter l'infrastructure comme du code. Deux outils de ce type sont Ansible et Terraform. Nous avons développé des exemples Ansible et Terraform que l'équipe DevOps peut utiliser avec Cloud Manager pour automatiser et intégrer Cloud Volumes ONTAP avec l'infrastructure-as-code.

https://["Afficher les échantillons d'automatisation"^].

Par exemple, vous pouvez utiliser des exemples de playbooks Ansible pour déployer Cloud Manager et Cloud Volumes ONTAP, créer un agrégat et créer un volume. Modifiez les échantillons pour votre environnement ou créez de nouveaux manuels de vente basés sur les échantillons.

* Liens connexes*

* https://["Blog sur le cloud NetApp : utilisation d'API REST de Cloud Manager avec un accès fédéré"^]
* https://["Blog sur le cloud NetApp : l'automatisation du cloud avec Cloud Volumes ONTAP et REST"^]
* https://["Blog sur le cloud NetApp : clonage automatisé des données pour le test des applications logicielles basé sur le cloud"^]
* https://["Blog NetApp : IAC (Infrastructure-as-Code) accéléré avec Ansible + NetApp"^]
* https://["NetApp thePub : gestion de la configuration et automatisation avec Ansible"^]
* https://["NetApp thePub : rôles pour l'utilisation d'Ansible ONTAP"^]

