---
sidebar: sidebar 
permalink: reference_networking_azure.html 
keywords: networking, network, requirements, connection, connections, vnet, security group, security groups, subnet, vpn, internet, proxy, HTTP, private, proxy server, routing, firewall, autosupport, connection, jump host, outbound, ports, blob, service endpoint 
summary: Vous devez configurer votre réseau Azure pour que les systèmes Cloud Volumes ONTAP puissent fonctionner correctement. 
---
= Configuration réseau requise pour Cloud Volumes ONTAP dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez configurer votre réseau Azure pour que les systèmes Cloud Volumes ONTAP puissent fonctionner correctement.

****
Vous recherchez la liste des terminaux auxquels Cloud Manager a besoin d'un accès ? Ils sont désormais gérés dans un seul emplacement. link:reference_networking_cloud_manager.html["Cliquez ici pour plus de détails"].

****
Accès Internet sortant pour Cloud Volumes ONTAP:: Cloud Volumes ONTAP requiert un accès Internet sortant pour envoyer des messages à NetApp AutoSupport, qui surveille de façon proactive l'état de votre stockage.
+
--
Les règles de routage et de pare-feu doivent autoriser le trafic AWS HTTP/HTTPS vers les terminaux suivants pour que Cloud Volumes ONTAP puisse envoyer les messages AutoSupport :

* \https://support.netapp.com/aods/asupmessage
* \https://support.netapp.com/asupprod/post/1.0/postAsup


--
Groupes de sécurité:: Vous n'avez pas besoin de créer de groupes de sécurité car Cloud Manager le fait pour vous. Si vous devez utiliser votre propre, reportez-vous à la section link:reference_security_groups_azure.html["Règles de groupe de sécurité"].
Connexion de Cloud Volumes ONTAP au stockage Azure Blob pour le hiérarchisation des données:: Si vous souhaitez transférer les données inactives vers un stockage Azure Blob, vous n'avez pas besoin de configurer un terminal de service VNet tant que Cloud Manager dispose des autorisations requises :
+
--
[source, json]
----
"Microsoft.Network/virtualNetworks/subnets/write",
"Microsoft.Network/routeTables/join/action",
----
Ces autorisations sont incluses dans la dernière version https://["Politique de Cloud Manager"].

Pour plus d'informations sur la configuration du Tiering des données, voir link:task_tiering.html["Tiering des données inactives vers un stockage objet à faible coût"].

--
Connexions aux systèmes ONTAP dans d'autres réseaux:: Pour répliquer des données entre un système Cloud Volumes ONTAP sur les systèmes Azure et ONTAP sur d'autres réseaux, vous devez disposer d'une connexion VPN entre Azure VNet et l'autre réseau, par exemple un VPC AWS ou votre réseau d'entreprise.
+
--
Pour obtenir des instructions, reportez-vous à la section https://["Documentation Microsoft Azure : créez une connexion de site à site dans le portail Azure"^].

--

