---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux,  svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk 
summary: Par défaut, les informations sur la configuration de Cloud Manager et de Cloud Volumes ONTAP peuvent vous aider à administrer les systèmes. 
---
= Configurations par défaut
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Par défaut, les informations sur la configuration de Cloud Manager et de Cloud Volumes ONTAP peuvent vous aider à administrer les systèmes.



== Configuration par défaut de Cloud Manager sous Linux

Si vous devez dépanner Cloud Manager ou votre hôte Linux, il peut vous aider à comprendre comment Cloud Manager est configuré.

* Si vous avez déployé Cloud Manager depuis NetApp Cloud Central (ou directement depuis AWS Marketplace ou Azure Marketplace), notez ce qui suit :
+
** Dans AWS, le nom d'utilisateur de l'instance Linux EC2 est ec2-user.
** Pour AWS et Azure, le système d'exploitation de l'image Cloud Manager est Red Hat Enterprise Linux 7.4 (HVM).
+
Le système d'exploitation n'inclut pas d'interface graphique. Vous devez utiliser un terminal pour accéder au système.



* Le dossier d'installation de Cloud Manager se trouve à l'emplacement suivant :
+
/opt/application/netapp/cloudmanager

* Les fichiers journaux se trouvent dans le dossier suivant :
+
/opt/application/netapp/cloudmanager/log

* Le service Cloud Manager s'appelle occm.
* Le service occm dépend du service MySQL.
+
Si le service MySQL est en panne, le service occm est également en panne.

* Cloud Manager installe les packages suivants sur l'hôte Linux, s'ils ne sont pas déjà installés :
+
** 7Zip
** AWSCLI
** Java
** Kubectl
** MySQL
** Tridentctl
** Wget






== Configuration par défaut pour Cloud Volumes ONTAP

La configuration par défaut de Cloud Volumes ONTAP peut vous aider à configurer et administrer vos systèmes, surtout si vous connaissez ONTAP, car la configuration par défaut de Cloud Volumes ONTAP est différente de ONTAP.

* Cloud Volumes ONTAP est disponible en tant que système à un seul nœud et en tant que paire HA dans AWS et Azure.
* Cloud Manager crée une SVM de service de données lorsqu'il déploie Cloud Volumes ONTAP. Bien que vous puissiez créer un autre SVM de service de données à partir de System Manager ou de l'interface de ligne de commande, plusieurs SVM de service de données ne sont pas pris en charge.
* Plusieurs interfaces réseau sont créées par défaut :
+
** Un LIF de gestion de cluster
** Un FRV intercluster
** Un LIF de gestion des nœuds
** Un LIF de données iSCSI
** Un LIF de données CIFS et NFS
+

NOTE: Le basculement LIF est désactivé par défaut pour Cloud Volumes ONTAP en raison des exigences d'EC2. La migration d'un LIF vers un port différent rompt le mappage externe entre les adresses IP et les interfaces réseau de l'instance, ce qui rend le LIF inaccessible.



* Cloud Volumes ONTAP envoie des sauvegardes de configuration à Cloud Manager via HTTPS.
* Lorsque vous êtes connecté à Cloud Manager, les sauvegardes sont accessibles depuis https://[]
* Cloud Manager définit quelques attributs de volume différemment des autres outils de gestion (System Manager ou CLI, par exemple).
+
Le tableau suivant répertorie les attributs de volume définis par Cloud Manager différemment des valeurs par défaut :

+
[cols="15,85"]
|===
| Attribut | Valeur définie par Cloud Manager 


| Mode Autosize | Grandir 


| Positionnement automatique maximum  a| 
1 000 pour cent


NOTE: L'administrateur Cloud Manager peut modifier cette valeur à partir de la page Paramètres.



| Style de sécurité | NTFS pour les volumes CIFS UNIX pour les volumes NFS 


| Style de garantie de l'espace | Aucune 


| Autorisations UNIX (NFS uniquement) | 776 
|===
+
Pour plus d'informations sur ces attributs, reportez-vous à la page _volume create_ man.





== Données de démarrage et de racine pour Cloud Volumes ONTAP

Outre le stockage des données utilisateur, Cloud Manager achète également du stockage cloud pour le démarrage et les données root sur chaque système Cloud Volumes ONTAP.



=== AWS

* Un disque SSD IOPS provisionné pour les données d'initialisation de Cloud Volumes ONTAP, soit environ 45 Go et 1 250 PIOPS
* Un disque SSD à usage général pour les données root de Cloud Volumes ONTAP, qui est d'environ 140 Go
* Un instantané EBS pour chaque disque d'initialisation et disque racine


Dans une paire HA, les deux nœuds Cloud Volumes ONTAP répliquent leur disque racine sur le nœud partenaire.



=== Azure

* Un disque SSD de stockage Premium pour les données d'initialisation de Cloud Volumes ONTAP, d'environ 73 Go
* Un disque SSD de stockage Premium pour les données root de Cloud Volumes ONTAP, qui est d'environ 140 Go
* Un snapshot Azure pour chaque disque d'initialisation et disque racine




=== Où résident les disques

Cloud Manager présente le stockage d'AWS et d'Azure comme suit :

* Les données d'amorçage résident sur un disque connecté à l'instance EC2 ou à la machine virtuelle Azure.
+
Ce disque, qui contient l'image d'amorçage, n'est pas disponible pour Cloud Volumes ONTAP.

* Les données root, qui contiennent la configuration du système et les journaux, résident dans aggr0.
* Le volume racine de la machine virtuelle de stockage (SVM) réside dans aggr1.
* Les volumes de données résident également dans aggr1.

