---
pagenav: false 
sidebar: sidebar 
permalink: task_getting_started_aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, tiering, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create 
summary: Vous pouvez commencer avec Cloud Volumes ONTAP dans AWS en effectuant quelques étapes rapides. 
---
= Mise en route de Cloud Volumes ONTAP dans AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez commencer à utiliser Cloud Volumes ONTAP dans AWS à partir de NetApp Cloud Central.



=== Configurez votre réseau

. Activez l'accès Internet sortant à partir du VPC cible pour que Cloud Manager et Cloud Volumes ONTAP puissent contacter plusieurs terminaux.
+
Cette étape est importante car Cloud Manager ne peut pas déployer Cloud Volumes ONTAP sans accès Internet sortant. Si vous devez limiter la connectivité sortante, reportez-vous à la liste des noeuds finaux pour link:reference_networking_cloud_manager.html#outbound-internet-access["Le gestionnaire Cloud"] et link:reference_networking_aws.html#general-aws-networking-requirements-for-cloud-volumes-ontap["Cloud Volumes ONTAP"].

. Configurez un terminal VPC sur le service S3.
+
Un point de terminaison VPC est requis si vous souhaitez transférer des données à froid de Cloud Volumes ONTAP vers un stockage objet économique.





=== Abonnez-vous à Cloud Volumes ONTAP depuis AWS Marketplace

[role="quick-margin-para"]
Abonnement de https://aws.amazon.com/marketplace/search/results?page=1&searchTerms=netapp+cloud+volumes+ontap["AWS Marketplace"^] est obligatoire pour accepter les termes du logiciel. Vous ne devez vous abonner qu'à partir du Marketplace. Le lancement de Cloud Volumes ONTAP n'importe où, mais Cloud Manager n'est pas pris en charge.



=== Fournissez les autorisations AWS requises

[role="quick-margin-para"]
Lorsque vous déployez Cloud Manager à partir de NetApp Cloud Central, vous devez utiliser un compte AWS qui dispose des autorisations nécessaires pour déployer l'instance.

. Accédez à la console IAM AWS et créez une règle en copiant et en collant le contenu du https://mysupport.netapp.com/cloudontap/iampolicies["Politique NetApp Cloud Central pour AWS"^].
. Associez la stratégie à l'utilisateur IAM.




=== Lancez Cloud Manager à partir de NetApp Cloud Central

[role="quick-margin-para"]
Le logiciel Cloud Manager est requis pour déployer et gérer Cloud Volumes ONTAP. Quelques minutes suffisent pour lancer une instance Cloud Manager à partir de https://cloud.netapp.com["Cloud Central"^].



=== Lancez Cloud Volumes ONTAP à l'aide de Cloud Manager

[role="quick-margin-para"]
Une fois Cloud Manager prêt, cliquez simplement sur Créer, sélectionnez le type de système que vous souhaitez lancer et suivez les étapes de l'assistant. Après 25 minutes, votre premier système Cloud Volumes ONTAP doit être opérationnel.

.Liens connexes
* link:concept_evaluating.html["L'évaluation"]
* link:reference_networking_cloud_manager.html["Configuration réseau requise pour Cloud Manager"]
* link:reference_networking_aws.html["Configuration réseau requise pour Cloud Volumes ONTAP dans AWS"]
* link:reference_security_groups.html["Règles de groupe de sécurité pour AWS"]
* link:task_adding_cloud_accounts.html["Ajout de comptes de fournisseurs de services clouds à Cloud Manager"]
* link:reference_permissions.html#what-cloud-manager-does-with-aws-permissions["Ce que fait Cloud Manager avec les autorisations AWS"]
* link:task_deploying_otc_aws.html["Lancement d'Cloud Volumes ONTAP dans AWS"]
* link:task_launching_aws_mktp.html["Lancement de Cloud Manager à partir d'AWS Marketplace"]

