---
sidebar: sidebar 
permalink: task_enabling_flash_cache.html 
keywords: cloud volumes ontap, aws, ec2, flash cache, read-intensive, read, random, databases, email, file services, c5d.4xlarge, c5d.9xlarge, r5d.2xlarge, compression, performance 
summary: 'Certains types d"instances EC2 incluent le stockage NVMe local, qui est utilisé par Cloud Volumes ONTAP comme Flash cache. Flash cache accélère l"accès aux données grâce à la mise en cache intelligente en temps réel des données utilisateur et des métadonnées NetApp lues récemment. Il est efficace pour les charges de travail exigeant une capacité de lecture aléatoire maximale, dont les bases de données, la messagerie et les services de fichiers.' 
---
= Activation de Flash cache sur Cloud Volumes ONTAP dans AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Certains types d'instances EC2 incluent le stockage NVMe local, que Cloud Volumes ONTAP utilise _Flash cache_. Flash cache accélère l'accès aux données grâce à la mise en cache intelligente en temps réel des données utilisateur et des métadonnées NetApp lues récemment. Il est efficace pour les charges de travail exigeant une capacité de lecture aléatoire maximale, dont les bases de données, la messagerie et les services de fichiers.


NOTE: La réactivation du cache après un redémarrage n'est pas prise en charge avec Cloud Volumes ONTAP.

.Étapes
. Sélectionnez l'un des types d'instances EC2 suivants, disponibles avec les licences Premium et BYOL :
+
** c5d.4xlarge
** c5d.9xlarge
** r5d.2xlarge


. Désactiver la compression sur tous les volumes.
+
La compression doit être désactivée sur tous les volumes pour tirer parti des améliorations des performances de Flash cache. Vous pouvez choisir aucune efficacité du stockage lors de la création d'un volume depuis Cloud Manager, ou encore créer un volume, puis http://["Désactiver la compression des données à l'aide de l'interface de ligne de commande"^].


