---
sidebar: sidebar 
permalink: task_uninstalling.html 
keywords: uninstalling, uninstall, reinstall 
summary: 'Cloud Manager inclut un script de désinstallation que vous pouvez utiliser pour désinstaller le logiciel pour résoudre les problèmes ou supprimer définitivement le logiciel de l"hôte.' 
---
= Désinstallation de Cloud Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager inclut un script de désinstallation que vous pouvez utiliser pour désinstaller le logiciel pour résoudre les problèmes ou supprimer définitivement le logiciel de l'hôte.

.Étapes
. Si vous souhaitez réinstaller Cloud Manager, sauvegardez la base de données avant de désinstaller le logiciel :
+
.. Dans le coin supérieur droit de la console Cloud Manager, cliquez sur la liste déroulante des tâches, puis sélectionnez *Outils*.
.. Cliquez sur *Backup* et enregistrez le fichier de sauvegarde sur votre ordinateur local.


. À partir de l'hôte Linux, exécutez le script de désinstallation :
+
*/opt/application/netapp/cloudmanager/bin/uninstall.sh [silencieux]*

+
_silent_ exécute le script sans vous demander de confirmer.


